version = 0.1
[default.deploy.parameters]
stack_name = "bff-stack"
resolve_s3 = true
s3_prefix = "bff-stack"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true

[production.deploy.parameters]
stack_name = "bff-stack"
resolve_s3 = true
s3_prefix = "bff-stack"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
